---
title: "TidyTuesday 2022-03-01"
output:
  html_document:
    df_print: paged
---

```{r}
require(usmap)
require(tidyverse)
stations <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-01/stations.csv')
```

```{r}
stations %>%
  glimpse()
```

```{r}
pct_e <- stations %>%
  mutate(Electric = case_when(
    is.na(FUEL_TYPE_CODE) ~ NA_real_,
    FUEL_TYPE_CODE == 'ELEC' ~ 1,
    TRUE ~ 0
  )) %>%
  group_by(STATE) %>%
  summarize(Percent_E = mean(Electric)*100,
            n = n())
pct_e
```

```{r}
statepop %>%
  left_join(pct_e, by=c("abbr"="STATE")) %>%
  plot_usmap(regions='states', data = ., values = "Percent_E") +
  scale_fill_viridis_c() +
  labs(title='Reliance on electricity as an alternate fuel source',
       subtitle="Electric charging dominates the Northeast",
       caption="@drkeithyoder. TidyTuesday 2022 Week 8. Data from US DOT.",
       fill="% Electric"
          ) +
  theme(plot.title = element_text(size=16),
        panel.background = element_rect(colour = "black"),
        legend.position = 'right')

ggsave('20220301.png', width=6, height=4, unit='in', bg='white')
```

```{r}
state_pct <- statepop %>%
  left_join(pct_e, b=c("abbr"="STATE")) %>% 
  filter(! "abbr" %in% c("AK", "HI"))
state_pct %>%
  arrange(n) %>%
  head(10)
```

```{r}
state_pct %>%
  arrange(desc(Percent_E)) %>%
  head(20)
```



